//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PholioVisualisation.UserData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fingertips_usersEntities : DbContext
    {
        public fingertips_usersEntities()
            : base("name=fingertips_usersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaList> AreaLists { get; set; }
        public virtual DbSet<AreaListAreaCode> AreaListAreaCodes { get; set; }
    }
}
