//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PholioVisualisation.UserData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AreaList()
        {
            this.AreaListAreaCodes = new HashSet<AreaListAreaCode>();
        }
    
        public int Id { get; set; }
        public string ListName { get; set; }
        public int AreaTypeId { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string PublicId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaListAreaCode> AreaListAreaCodes { get; set; }
    }
}
